name = "fso-tables-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-06-21"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "fso_table_database"
database_name = "fso-modoption-d1-db"
database_id = "facc22be-76a1-43c2-8655-0b043059f646"

# wrangler.toml (wrangler v3.78.6^)
# [observability]
# enabled = true